# Generated by Django 5.1.1 on 2024-09-04 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resident", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="residentvisitor",
            name="check_in",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="residentvisitor",
            name="check_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
